### ISSUE TITLE
Example program

### ISSUE THREAD

**Issue by nordseele** [rppicomidi/pio_midi_uart_lib#1]
Hi, 
Thanks a lot for sharing this library!
Would it be possible to provide a small example program please ? Or is it used in any of your other repositories already ?

All the best,

**Comment by rppicomidi** [comment]
@nordseele Thanks for your interest. Yes, a small example exists. It is used in [midi-multistream2usbdev](https://github.com/rppicomidi/midi-multistream2usbdev), which is a 2 in 6 out DIN MIDI to USB device MIDI interface.

**Comment by nordseele** [comment]
Great!
I wasn't sure how to retrieve and handle the MIDI bytes with `pio_midi_uart_poll_rx_buffer`, so I took inspiration from the implementation done for your other library, `midi_uart_lib`. I hadn't seen your **midi-multistream2usbdev** project :) Thanks again for all these very useful libraries.
